name: Build and Test Node JS Service

on:
  workflow_call:
    inputs:
      service-name:
        description: "Node JS service name"
        required: true
        type: string
      run-tests:
        description: "Run test suite"
        required: false
        default: true
        type: boolean
      slack-test-failures:
        description: "Notify test suite failures in Slack"
        required: false
        default: false
        type: boolean
      publish-built-image:
        description: "Publish built image to AWS ECR"
        required: false
        default: false
        type: boolean
      aws-ecr-image-tag:
        description: "AWS ECR image tag"
        required: false
        type: string
    secrets:
      docker-build-secrets:
        description: "Build secrets passed as args to docker"
        required: false
      aws-access-key-id:
        description: "AWS access key ID"
        required: true
      aws-secret-access-key:
        description: "AWS secret access key"
        required: true
      aws-region:
        description: "AWS region"
        required: true
      aws-ecr-repo:
        description: "AWS ECR repository name"
        required: false
      slack-webhook-url:
        description: "Slack webhook URL"
        required: false
      slack-webhook-channel:
        description: "Slack webhook channel"
        required: false

jobs:
  build_and_test:
    name: Build and Test

    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.github.event_name }}-${{ github.head_ref || github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3

      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: ${{ inputs.service-name }}
          build-args: ${{ secrets.docker-build-secrets }}

      - name: Run tests
        if: "${{ inputs.run-tests }}"
        run: docker run --env NODE_ENV=test ${{ inputs.service-name }} yarn test
        timeout-minutes: 3

      - name: Notify test suite failures
        if: "failure() && inputs.slack-test-failures && inputs.run-tests"
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.slack-webhook-url }}
          SLACK_CHANNEL: ${{ secrets.slack-webhook-channel }}
          SLACK_USERNAME: Github Bot
          SLACK_MESSAGE: Test suite failures detected in ${{ inputs.service-name }} (${{ github.event.head_commit.message }})!
          SLACK_COLOR: danger

      - name: Configure AWS credentials
        if: "inputs.publish-built-image"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ secrets.aws-region }}

      - name: Login to ECR
        if: "inputs.publish-built-image"
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Publish built image to ECR
        if: "inputs.publish-built-image"
        env:
          PUBLISH_IMAGE_TAG: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.aws-ecr-repo }}:${{ inputs.aws-ecr-image-tag }}
        run: docker tag ${{ inputs.service-name }} $PUBLISH_IMAGE_TAG && docker push $PUBLISH_IMAGE_TAG
