name: Checkstyle with ESLisnt

on:
  workflow_call:
    inputs:
      notify-failure:
        description: "Notify eslint check failures via Slack"
        required: true
        default: false
        type: boolean
    secrets:
      slack-webhook-url:
        description: "Slack webhook URL"
        required: false
      slack-webhook-channel:
        description: "Slack webhook channel"
        required: false

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-v1-${{ hashFiles('.nvmrc') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-v1

      - name: Setup Node JS
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: yarn

      - name: Run eslint
        run: yarn eslint

      - name: Eslint failed
        if: "failure() && inputs.notify-failure"
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.slack-webhook-url }}
          SLACK_CHANNEL: ${{ secrets.slack-webhook-channel }}
          SLACK_USERNAME: Github Bot
          SLACK_MESSAGE: Eslint checks failed for ${{ github.repository }} (${{ github.event.head_commit.message }})!
          SLACK_COLOR: danger
