name: Checkstyle with ESLint

on:
  workflow_call:
    inputs:
      slack-check-failures:
        description: "Notify eslint check failures via Slack"
        required: true
        default: false
        type: boolean
    secrets:
      slack-webhook-url:
        description: "Slack webhook URL"
        required: false
      slack-webhook-channel:
        description: "Slack webhook channel"
        required: false

jobs:
  eslint:
    name: ESLint

    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Read Node JS version from .nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-v1-${{ steps.nvm.outputs.node_version }}
          restore-keys: |
            ${{ runner.os }}-node_modules-v1

      - name: Setup Node JS
        uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE_VERSION }}"

      - name: Install dependencies
        run: yarn

      - name: Run eslint
        run: ./node_modules/.bin/eslint .

      - name: Eslint failed
        if: "failure() && inputs.slack-check-failures"
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.slack-webhook-url }}
          SLACK_CHANNEL: ${{ secrets.slack-webhook-channel }}
          SLACK_USERNAME: Github Bot
          SLACK_MESSAGE: Eslint checks failed for ${{ github.repository }} (${{ github.event.head_commit.message }})!
          SLACK_COLOR: danger
